### ISSUE TITLE
index.htmlから飛べる「使い方」ページが古い

### ISSUE THREAD

**Issue by kuriko** [DDRAGON/raise#12]
![default](https://cloud.githubusercontent.com/assets/5752457/5842776/09995440-a1eb-11e4-8724-1380e2fb9134.JPG)
oddssystemのHOWTOが最新なので合わせるか、ページ自体消してもよいかも

**Comment by DDRAGON** [comment]
最新の方に合わせました。
デザインもなんとかするかー
