### ISSUE TITLE
screenSizeフォームの表示幅が内容物より狭い

### ISSUE THREAD

**Issue by kuriko** [DDRAGON/raise#14]
![default](https://cloud.githubusercontent.com/assets/5752457/5842746/baf84d82-a1ea-11e4-9cda-0c2c09bef113.JPG)
View Layout に幅を合わせるなら `select(class="selectpicker" data-width="113px" id="changeScreenSize")` かな

**Comment by DDRAGON** [comment]
(・∀・)ｲｲﾈ!!
直した。
