### ISSUE TITLE
最後のプレイヤーのハンドに直前のカードを指定すると登録されてしまう

### ISSUE THREAD

**Issue by kuriko** [DDRAGON/raise#4]
こんな状態になります
http://gyazo.com/5b37e00fae9becf014937868360cf7a1

**Comment by DDRAGON** [comment]
直したよん♪

**Comment by DDRAGON** [comment]
バグ報告ありがとう！
コード見直したらたしかにそのとうりでした。

**Comment by kuriko** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
